apiVersion: 1
profiles:
  - name: local
    connection:
      host: localhost
      user: douglas
      destination: /tmp/piaas
    ignoreFile: .piaasignore
  - name: dev
    connection:
      host: remote
      user: foo
      destination: ~/src
