apiVersion: 1
profiles:
  - name: cent
    connection:
      host: centaurium.sohoffice.com
      user: piaas
      destination: ~/src
  - name: win
    connection:
      host: localhost
      user: IEUser
      destination: C:/Users/IEUser/src
